### ISSUE TITLE
Obsolete location

### ISSUE THREAD

**Issue by foxt7ot** [ContextQuickie/ContextQuickie#11] opened 2016-11-30 11:38 UTC
While installing plugin I am getting location error. Seems like location has been changed but not been updated in plugin ```

Unable to read repository at http://contextquickie.github.io/ContextQuickie/
http://contextquickie.github.io/ContextQuickie/ is not a valid repository location
```

**Comment by ContextQuickie** [comment] 2016-11-30 20:11
I cannot reproduce the issue. What I did: Download a fresh eclipse package (eclipse-cpp-neon-1a-win32-x86_64.zip), start it with a new workspace and install ContextQuickie via Help -> Install New Software and adding the update site you mentioned. The plugin can be installed at my computer.
Do you have any further information regarding this issue? Which eclipse version do you use and how do you install the plugin?

**Comment by ContextQuickie** [comment] 2017-01-07 10:34
Do you have any comments regarding this issue? As I cannot reproduce it, I'll close it.

**Closed** 2017-01-13 21:17 UTC
