### ISSUE TITLE
Two issues with Eclipse Photon

### ISSUE THREAD

**Issue by toutzhang** [ContextQuickie/ContextQuickie#19] opened 2018-07-13 12:18 UTC
1. "Tortoise SVN" is always displaying on popup menu, even disabled all the functions at Preferences;
![a](https://user-images.githubusercontent.com/40381675/42691261-deed3c0c-86d9-11e8-8539-14b375877724.png)

2. Context menu takes 3 or more seconds to pop up.
When I used Oracle Java Mission Control to flight record what happened, I found that most of the time was spent on the following methods:
CompareToRightDynamic.<init>()
BeyondCompare.readRegistry()
Registry.readKey(String, String)
![b](https://user-images.githubusercontent.com/40381675/42691279-f0b9da3a-86d9-11e8-970e-dd1681097d21.png)

**Comment by ContextQuickie** [comment] 2018-07-15 08:54
I disabled the Tortoise SVN menu entries if Tortoise SVN is disabled in the settings. The fix will be included in the next release.
I did some tests regarding the performance. I cannot reproduce the 3 seconds delay but maybe it depends on the used environment. 
I also detected that the Beyond compare registry is read if the plugin is disabled (unexpected behavoir of eclipse). Reading out the registry can take very long as it calls an external process and waits until it is finished, there are some options for the impementation:
- Do not read out Beyond Compare settings if it is disabled in the settings
- Implement some kind of read cache to reduce the amount of process calls

Is Beyond Compare support enabled in your configuration?

**Comment by toutzhang** [comment] 2018-07-16 01:06
No. To be precise, wheter Beyond Compare support enabled or not, the lantency is the same.
Registry cache may be a very good idea.

**Comment by ContextQuickie** [comment] 2018-07-16 15:33
which plugins do you currently use?

**Comment by toutzhang** [comment] 2018-07-17 01:54
I used ContextQuickie_0.8.3.201807091746.

Other plugins I have installed in eclipse-jee-photon-R-win32-x86_64 includes:
AnyEditTools_2.7.1.201709201439
com.github.spotbugs.plugin.eclipse_3.1.5.r201806132012-cbbf0a5
net.harawata.mybatipse_1.1.1.201804151813
io.github.pyvesb.notepad4e_1.5.1.201806201645

**Comment by ContextQuickie** [comment] 2018-07-17 18:58
I tried to reproduce the long delay with a fresh installation of eclipse photon. I saw that there is a delay but only about maximum 1 second.
Attached you'll find a version which doesn't read out registry values for Beyond Compare if it's not enabled in the preferences. Does this improve the performance? 
Other questions:
- Which features of ContextQuickie do you use? Beyond Compare, Tortoise SVN/Git?
- Can you tell me about your project size, especially the number of (linked) files/folders in the project? Are there hundreds, thousands?
[ContextQuickie_0.8.5.201807172048.zip](https://github.com/ContextQuickie/ContextQuickie/files/2202963/ContextQuickie_0.8.5.201807172048.zip)

**Comment by toutzhang** [comment] 2018-07-18 02:12
I tried the new version. Yes, the performance improvement is noticeable when Tortoise Git enabled. But the delay still obvious when Beyond Compare enabled.

I'm using both Beyond Compare and Tortoise Git, but SVN.
Our typical project has about two thousand files and two hundred and fifty folders.

**Comment by ContextQuickie** [comment] 2018-07-18 18:26
Ok, I did a short measurement for reading out the registry on my machine and got the following results:
With the current implementation: 30-50ms
With JNA: about 1ms
I'll check if I can switch to JNA for this plugin.
Another question from my side: is there any difference in performance if you enable or disable the follwoing preferences:
![image](https://user-images.githubusercontent.com/15061118/42900283-cf2daae8-8ac8-11e8-957d-38b1ed47fab5.png)

**Comment by toutzhang** [comment] 2018-07-19 01:35
I tested the two checkboxes, no difference.
JNA maybe a perfect choice.

**Comment by ContextQuickie** [comment] 2018-07-22 10:56
Attached you'll find an implementation with JNI (JNA broke compatibilty with older Eclipse versions), can you check if it is working and if there are any performance improvements?
[ContextQuickie_0.8.5.201807221245.zip](https://github.com/ContextQuickie/ContextQuickie/files/2216913/ContextQuickie_0.8.5.201807221245.zip)

**Comment by toutzhang** [comment] 2018-07-25 12:35
Yes, it works fine.

**Closed** 2018-07-25 17:49 UTC
